site_name: IIFLapis
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - 'Usage':
        - 'Authentication': 'usage/auth.md'
        - 'Placing an order': 'usage/place.md'
        - 'Modiying an order': 'usage/modify.md'
        - 'Canceling an order': 'usage/cancel.md'
        - 'Fetching  Market Feed Information': 'usage/mf.md'
        - 'Fetching information': 'usage/info.md'
        
theme: 
    name: material
    features:
        - instant
markdown_extensions:
    - codehilite:
        guess_lang: true
